package transformerconvertors2.common.resources;

import core.api.metadata.IMetadata;
import core.helpers.ChatHelper;
import cpw.mods.fml.common.ModContainer;
import net.minecraft.util.EnumChatFormatting;

import java.util.ArrayList;
import java.util.List;

/**
 * Created by Master801 on 10/19/2014.
 * @author Master801
 */
public final class TransformerConvertors2Metadata implements IMetadata {

    @Override
    public List<String> getAuthorList() {
        final List<String> list = new ArrayList<String>();
        list.add(ChatHelper.colourString(EnumChatFormatting.AQUA, "Master801"));
        list.add(ChatHelper.colourString(EnumChatFormatting.DARK_PURPLE, "RubenBackX"));
        list.add(ChatHelper.colourString(EnumChatFormatting.RED, "Castiel Angelow"));
        return list;
    }

    @Override
    public boolean isAutoGenerated() {
        return false;
    }

    @Override
    public List<ModContainer> getChildMods() {
        return null;
    }

    @Override
    public List<String> getCredits() {
        final List<String> list = new ArrayList<String>();
        list.add(ChatHelper.colourString(EnumChatFormatting.DARK_BLUE, "Snyke7"));
        list.add(ChatHelper.colourString(EnumChatFormatting.GOLD, "Kye_Duo"));
        list.add(ChatHelper.colourString(EnumChatFormatting.DARK_PURPLE, "RubenBackX"));
        list.add(ChatHelper.colourString(EnumChatFormatting.RED, "Castiel Angelow"));
        list.add(ChatHelper.colourString(EnumChatFormatting.DARK_GREEN, "Shadowranger"));
        list.add(ChatHelper.colourString(EnumChatFormatting.DARK_AQUA, "adamRos"));
//        credits.add("RubenBackX for helping me fix the gui crashing and mis-alignment bug  (in the pre-pre-alpha versions!)");
//        credits.add("adamRos for his original Electric-Engine code");
//        credits.add("And lastly, Snyke7 for making such an OP mod!");
        return list;
    }

    @Override
    public String getDescription() {
        return "Convert energy to other energies! Plus random junk.";
    }

    @Override
    public String getLogo() {
        return "/custom_resources/textures/Transformer_Convertors_2-Logo.png";
    }

    @Override
    public String getModID() {
        return ChatHelper.colourString(EnumChatFormatting.AQUA, ConvertorResources.TC2_MOD_ID);
    }

    @Override
    public String getModName() {
        return ConvertorResources.TC2_NAME;
    }

    @Override
    public String getParentMod() {
        return null;
    }

    @Override
    public String[] getScreenShots() {
        return new String[0];
    }

    @Override
    public String getUpdateURL() {
        return null;
    }

    @Override
    public String getURL() {
        return null;
    }

    @Override
    public String getModVersion() {
        return ChatHelper.colourString(EnumChatFormatting.AQUA, ConvertorResources.TC2_VERSION);
    }

}
